## Import Dataset 

In [14]:
import numpy as np
import pandas as pd

In [2]:
temp_df = pd.read_csv('IMDB Dataset.csv')

In [7]:
df = temp_df.iloc [:16000] 

In [8]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [9]:
df['sentiment'].value_counts()

sentiment
negative    8101
positive    7899
Name: count, dtype: int64

In [10]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [11]:
df.duplicated().sum()

44

In [12]:
df.drop_duplicates(inplace = True)

C:\Users\smrts\AppData\Local\Temp\ipykernel_18220\3424306917.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace = True)


In [13]:
df.duplicated().sum()

0

### Basic preprocessing
#### remove tags
#### lowercase
#### remove stopwords

In [17]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [19]:
df['review'] [1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [18]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\smrts\AppData\Local\Temp\ipykernel_18220\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [20]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
15995  beautifully constructed, "Traffik" tells the s...  positive
15996  Just re-saw this last night and to put it blun...  negative
15997  This show was absolutely great, and I always l...  positive
15998  Seriously - avoid this movie at any cost. I ju...  negative
15999  Recap: Not entirely familiar with the Shakespe...  negative

[15956 rows x 2 columns]

In [21]:
df['review'] = df['review'].apply(lambda x:x.lower())

C:\Users\smrts\AppData\Local\Temp\ipykernel_18220\740760900.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [24]:
import nltk
nltk.download('stopwords')
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\smrts\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
C:\Users\smrts\AppData\Local\Temp\ipykernel_18220\1969471839.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [25]:
df

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production. filming technique...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
15995  beautifully constructed, "traffik" tells story...  positive
15996  re-saw last night put bluntly: "style instead ...  negative
15997  show absolutely great, always look forward wat...  positive
15998  seriously - avoid movie cost. saw first "sneak...  negative
15999  recap: entirely familiar shakespeare story mac...  negative

[15956 rows x 2 columns]

In [26]:
X = df.iloc[:, 0:1]
Y = df['sentiment']

In [27]:
X

review
0      one reviewers mentioned watching 1 oz episode ...
1      wonderful little production. filming technique...
2      thought wonderful way spend time hot summer we...
3      basically there's family little boy (jake) thi...
4      petter mattei's "love time money" visually stu...
...                                                  ...
15995  beautifully constructed, "traffik" tells story...
15996  re-saw last night put bluntly: "style instead ...
15997  show absolutely great, always look forward wat...
15998  seriously - avoid movie cost. saw first "sneak...
15999  recap: entirely familiar shakespeare story mac...

[15956 rows x 1 columns]

In [28]:
Y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
15995    positive
15996    negative
15997    positive
15998    negative
15999    negative
Name: sentiment, Length: 15956, dtype: object

now after preprocessing steps and separating x and y. 
convert the reviews column ie Y into numbers 

In [29]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

In [30]:
Y

array([1, 1, 1, ..., 1, 0, 0])

now split data for training and testing separately 

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train , Y_test = train_test_split(X,Y, test_size = 0.2, random_state =1)

In [33]:
X_train.shape

(12764, 1)

have 12.5k approx as training data and rest 3.5k r testing data

In [34]:
# Applying Bow
from sklearn.feature_extraction.text import CountVectorizer

In [35]:
cv = CountVectorizer()

In [37]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()
# toarray used bcz sparse array m o/p aata h usko numpy array m convert kr dia 

In [38]:
X_train_bow.shape

(12764, 58842)

In [39]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_bow, Y_train)

GaussianNB()

In [42]:
Y_pred = gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(Y_test, Y_pred)

0.643483709273183

In [43]:
confusion_matrix(Y_test, Y_pred)

array([[1237,  415],
       [ 723,  817]], dtype=int64)

In [45]:
# after bag of words 
# Random Forest to check if it gives better result
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_bow, Y_train)
Y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test, Y_pred)

0.8424185463659147

In [46]:
cv = CountVectorizer(max_features = 6000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()
rf.fit(X_train_bow, Y_train)
Y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test, Y_pred)

0.8380325814536341

In [47]:
# using n-grams
cv = CountVectorizer(ngram_range = (1,2), max_features = 6000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()
rf.fit(X_train_bow, Y_train)
Y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test, Y_pred)

0.8405388471177945

### Using Tf-Idf

In [48]:
# tf-idf usually used in info retrieval but using here to check the accuarcy
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
tfidf = TfidfVectorizer()

In [51]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [52]:
rf = RandomForestClassifier()
rf.fit(X_train_bow, Y_train)
Y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test, Y_pred)

0.8389724310776943

## Word2Vec

In [53]:
import gensim

In [54]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [55]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [56]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2
)

In [57]:
model.build_vocab(story)

In [58]:
model.train(story, total_examples = model.corpus_count, epochs = model.epochs)

(9414841, 9915485)

In [59]:
len(model.wv.index_to_key)

39160

In [60]:
def document_vector(doc):
    #remove out-of-vocab words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis = 0)

In [61]:
document_vector(df['review'].values[0])

array([-0.08581927,  0.06902014,  0.04575795,  0.05396441,  0.28717956,
       -0.5708622 ,  0.15296495,  0.62412274,  0.13952535, -0.20891446,
       -0.00845745, -0.52210474, -0.24524312,  0.13048387,  0.22265387,
       -0.07273819,  0.15596484, -0.24311355,  0.05823059, -0.43402708,
        0.22789603, -0.01831406,  0.00403071, -0.08058593, -0.24611785,
       -0.13160716, -0.0612488 , -0.36702946, -0.36351562,  0.0075481 ,
        0.6981371 , -0.03979649, -0.08865424, -0.41000056, -0.19195084,
        0.20462969,  0.11570145, -0.07483418, -0.384732  , -0.77462816,
       -0.01475111, -0.19754684, -0.18413164, -0.14619282,  0.23711991,
       -0.09913079, -0.24729447, -0.03533679,  0.19703092,  0.31930614,
        0.15340199, -0.3352413 , -0.23926784, -0.13445798,  0.07403009,
        0.06602594,  0.40308246,  0.09261712, -0.40036178, -0.01748401,
       -0.0660167 ,  0.02001804, -0.191804  ,  0.0071057 , -0.39258042,
        0.41734964,  0.19758609,  0.21894534, -0.3682515 ,  0.25

In [62]:
from tqdm import tqdm

In [63]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|████████████████████████████████████████████████████████████████████████████| 15956/15956 [19:55<00:00, 13.35it/s]


In [66]:
X = np.array(X)

In [67]:
X.shape

(15956, 100)

In [69]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

Y = encoder.fit_transform(df['sentiment'])

In [70]:
Y

array([1, 1, 1, ..., 1, 0, 0])

In [71]:
rf = RandomForestClassifier()
rf.fit(X_train_bow, Y_train)
Y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test, Y_pred)

0.8389724310776943